# https://hub.docker.com/_/alpine
FROM alpine:latest
LABEL org.opencontainers.image.authors="githubfoam"


RUN apk --update add \
    git \
    strace \
    less \
    openssh && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*

#docker run --privileged=true -it --rm --name alpine-sshfs sshfs-image
RUN apk update && apk add sshfs && sshfs -V

